name: ct2mri
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.11.17=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hff52083_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.1.4=hd590300_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - psutil=5.9.5=py310h2372a71_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pyzmq=25.1.1=py310h795f18f_2
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.3.3=py310h2372a71_1
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backoff==2.2.1
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - clip==0.2.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - deprecated==1.2.14
      - diffusers==0.25.1
      - docker-pycreds==0.4.0
      - dominate==2.9.1
      - einops==0.7.0
      - elasticdeform==0.5.0
      - et-xmlfile==1.1.0
      - filelock==3.12.2
      - flatbuffers==23.5.26
      - fonttools==4.42.0
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - googleapis-common-protos==1.62.0
      - grpcio==1.59.0
      - h5py==3.9.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - humanize==4.9.0
      - idna==3.4
      - imageio==2.31.1
      - imbalanced-learn==0.11.0
      - imblearn==0.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - lightning-utilities==0.10.0
      - littleutils==0.2.2
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - natsort==8.4.0
      - networkx==3.1
      - nibabel==5.1.0
      - numpy==1.25.2
      - nvidia-ml-py==12.535.77
      - nvitop==1.2.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.14.1
      - onnxruntime==1.16.0
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.8.0.76
      - openpyxl==3.1.2
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - outdated==0.2.2
      - packaging==23.1
      - pandas==2.0.3
      - pandas-flavor==0.6.0
      - patsy==0.5.3
      - pillow==10.0.0
      - pingouin==0.5.3
      - piq==0.8.0
      - pretrained-backbones-unet==0.0.1
      - protobuf==4.24.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pycompare==1.5.4
      - pyparsing==3.0.9
      - python-graphviz==0.20.1
      - pytorch-fid==0.3.0
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - qudida==0.0.4
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.11.1
      - seaborn==0.12.2
      - segment-anything==1.0
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - simpleitk==2.3.1
      - smmap==5.0.1
      - statsmodels==0.14.0
      - sympy==1.12
      - synapseclient==4.0.0
      - tabulate==0.9.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2023.8.12
      - timm==0.6.12
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+cu116
      - torchio==0.19.3
      - torchmetrics==1.2.1
      - torchsummary==1.5.1
      - torchvision==0.14.1+cu116
      - torchviz==0.0.2
      - tqdm==4.66.1
      - typer==0.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==1.26.18
      - wandb==0.16.2
      - werkzeug==3.0.0
      - wrapt==1.16.0
      - xarray==2023.8.0
      - yarl==1.9.4
prefix: /home/x/.conda/envs/ct2mri
